name: itq_utils
description: Collection of Widgets and helpful Methods that every developer needs.
version: 1.0.1
#homepage: https://iTechQua.github.io
repository: https://github.com/iTechQua/itq_utils
issue_tracker: https://github.com/iTechQua/itq_utils/issues
funding:
  - https://www.github.com/sponsors/iTechQua

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.3
  fluttertoast: ^8.2.8
  connectivity_plus: ^6.1.0
  http: ^1.2.2

  version: ^3.0.2
  xml: ^6.5.0
  intl: ^0.19.0
  html: ^0.15.5
  package_info_plus: ^8.1.1
  url_launcher: ^6.1.12
  device_info_plus: ^11.1.1
  os_detect: ^2.0.2

dev_dependencies:
  lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.itechqu.itq_utils
        pluginClass: ITQUtilsPlugin
      ios:
        pluginClass: ITQUtilsPlugin
      linux:
        pluginClass: itq_utils_plugin
      macos:
        pluginClass: ITQUtilsPlugin
      windows:
        pluginClass: ITQUtilsPlugin

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: fonts/LineAwesome.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lottie/

topics:
  - widgets
  - extensions
  - utils
  - chatgpt
  - sharedpreference