name: itq_utils
description: Collection of Widgets and helpful Methods that every developer needs.
version: 2.0.5
#homepage: https://iTechQua.github.io
repository: https://github.com/iTechQua/itq_utils
issue_tracker: https://github.com/iTechQua/itq_utils/issues
funding:
  - https://www.github.com/sponsors/iTechQua

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.3
  fluttertoast: ^8.2.8
  connectivity_plus: ^6.1.0
  http: ^1.2.2
  cached_network_image: ^3.2.3

  version: ^3.0.2
  xml: ^6.5.0
  intl: ^0.19.0
  html: ^0.15.5
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.12
  device_info_plus: ^10.1.0
  os_detect: ^2.0.2
  path_provider: ^2.0.15
  permission_handler: ^11.3.0
  path_drawing: ^1.0.1

  flutter_chat_types: ^3.6.2
  diffutil_dart: ^4.0.1
  photo_view: ^0.14.0
  scroll_to_index: ^3.0.1
  visibility_detector: ^0.4.0+2
  flutter_link_previewer: ^3.2.2
  flutter_parsed_text: ^2.2.1
  meta: ^1.11.0
  equatable: ^2.0.5

  pdf: ^3.11.1
  syncfusion_flutter_core: ^27.2.5
  syncfusion_flutter_datagrid: ^27.2.5
  syncfusion_flutter_xlsio: ^27.2.5
  universal_html: ^2.2.4

  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.0.0
  timezone: ^0.10.0
  image: ^4.3.0
  path: ^1.8.3

  plugin_platform_interface: ^2.1.8
  web: ^1.1.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.itechqu.itq_utils
        pluginClass: ITQUtilsPlugin
      ios:
        pluginClass: ITQUtilsPlugin
      linux:
        pluginClass: itq_utils_plugin
      macos:
        pluginClass: ITQUtilsPlugin
      windows:
        pluginClass: ITQUtilsPlugin

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: fonts/LineAwesome.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lottie/
    - assets/app/

topics:
  - widgets
  - extensions
  - utils
  - chatgpt
  - sharedpreference