name: itq_utils
description: Collection of Widgets and helpful Methods that every developer needs.
version: 2.2.2
#homepage: https://iTechQua.github.io
repository: https://github.com/iTechQua/itq_utils
issue_tracker: https://github.com/iTechQua/itq_utils/issues
funding:
  - https://www.github.com/sponsors/iTechQua

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: '>=0.0.1 <3.0.0'
  fluttertoast: '>=7.0.0 <10.0.0'
  connectivity_plus: '>=5.0.0 <7.0.0'
  http: '>=0.0.1 <3.0.0'
  cached_network_image: '>=0.0.1 <5.0.0'
  google_fonts: '>=5.0.0 <7.0.0'

  version: '>=0.0.1 <5.0.0'
  xml: '>=0.0.1 <9.0.0'
  intl: '>=0.0.1 <1.0.0'
  html: '>=0.0.1 <1.1.0'
  package_info_plus: '>=0.0.1 <10.0.0'
  url_launcher: '>=0.0.1 <7.0.0'
  device_info_plus: '>=0.0.1 <13.0.0'
  os_detect: '>=0.0.1 <5.0.0'
  path_provider: '>=0.0.1 <3.0.0'
  permission_handler: '>=0.0.1 <13.0.0'
  path_drawing: '>=0.0.1 <4.0.0'

  flutter_chat_types: '>=0.0.1 <6.0.0'
  diffutil_dart: '>=0.0.1 <7.0.0'
  photo_view: '>=0.0.1 <2.0.0'
  scroll_to_index: '>=0.0.1 <5.0.0'
  visibility_detector: '>=0.0.1 <2.0.0'
  flutter_link_previewer: '>=0.0.1 <6.0.0'
  flutter_parsed_text: '>=0.0.1 <4.0.0'
  meta: '>=0.0.1 <4.0.0'
  equatable: '>=0.0.1 <4.0.0'

  pdf: '>=0.0.1 <6.0.0'
  syncfusion_flutter_core: '>=20.0.0 <32.0.0'
  syncfusion_flutter_datagrid: '>=20.0.0 <32.0.0'
  syncfusion_flutter_xlsio: '>=20.0.0 <32.0.0'
  universal_html: '>=0.0.1 <7.0.0'

  plugin_platform_interface: '>=0.0.1 <6.0.0'
  web: '>=0.0.1 <2.0.0'
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.itechqu.itq_utils
        pluginClass: ItqUtilsPlugin
      ios:
        pluginClass: ItqUtilsPlugin
      linux:
        pluginClass: ItqUtilsPlugin
      macos:
        pluginClass: ItqUtilsPlugin
      windows:
        pluginClass: ItqUtilsPluginCApi
      web:
        pluginClass: ItqUtilsWeb
        fileName: itq_utils_web.dart

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: fonts/LineAwesome.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lottie/
    - assets/app/

topics:
  - widgets
  - extensions
  - utils
  - chatgpt
  - sharedpreference