/// Flutter icons EmergentIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EmergentIcons
///      fonts:
///       - asset: fonts/EmergentIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
library;
import 'package:flutter/widgets.dart';

class EmergentIcons {
  EmergentIcons._();

  static const _itqFontFam = 'EmergentIcons';
  static const _itqFontPkg = "itq_utils";

  static const IconData check =
      IconData(0xe800, fontFamily: _itqFontFam, fontPackage: _itqFontPkg);
}
